@ECHO OFF

SETLOCAL ENABLEDELAYEDEXPANSION

SET PROJECT_PATH=%1

IF NOT EXIST %PROJECT_PATH%\Princesses\ (
     MKDIR %PROJECT_PATH%\Princesses
)
XCOPY /S /Y .\dir_Girls\ %PROJECT_PATH%\Princesses\ > NUL

SET PROJECT_PATH_SPACE=%PROJECT_PATH:\= %
FOR %%t IN ( %PROJECT_PATH_SPACE% ) DO (
     SET PROJECT_NAME=%%t
)

SET DEFAULT=_PROJECT_NAME_
SET REPLACEMENT=%PROJECT_NAME%

IF EXIST %1\%PROJECT_NAME%.gpr (
     DEL %1\%PROJECT_NAME%.gpr
)
FOR /F "DELIMS=" %%t IN ( .\dir_Modules\Template.gpr ) DO (
     SET LINE=%%t
     ECHO !LINE:%DEFAULT%=%REPLACEMENT%!>>%1\%PROJECT_NAME%.gpr
)
